RivetSTAR_2010_I837075.so: STAR_2010_I837075.cc
	docker run -i  --rm  -u `id -u ${USER}`:`id -g`  -v ${PWD}:${PWD} -w ${PWD}  hepstore/rivet:3.1.2 rivet-build RivetSTAR_2010_I837075.so STAR_2010_I837075.cc
